[[language]]
indent = {tab-width = 2, unit = "  "}

[language-server.clangd]
command = "clangd"
args = ["--clang-tidy",
 "--experimental-modules-support",
 "--malloc-trim",
 "-j=8",
 "--background-index",
]
