[manager]
sort_by = "extension"
sort_sensitive = true
sort_dir_first = true
show_hidden = true
show_symlink = true

[open]
prepend_rules = [
    { name = "*.pdf", use = "open-pdf" },
    { name = "*.desktop", use = "run" },
    { name = "*.py", use = "run" },
    { name = "*.sh", use = "run" },
    { name = "*.bash", use = "run" },
    { name = "*.zsh", use = "run" },
    { name = "*.fish", use = "run" },
    { name = "*.dash", use = "run" },
]

[opener]
open-pdf = [
    { run = 'okular "$@"', orphan = true, desc = "Open PDF" },
]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit with NeoVim" },
    { run = 'libreoffice "$@"', orphan = true, desc = "Edit with LibreOffice" },
]
run = [
    { run = '"$@"', desc = "Run executable" },
]
