return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "bash",
            "c",
            "cmake",
            "cpp",
            "dockerfile",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "hyprlang",
            "json",
            "lua",
            "make",
            "markdown",
            "nu",
            "rust",
        },
        sync_install = true,
        auto_install = true,
    },
}
